import RecipesForm from '@/components/RecipesForm'
import RecipesFormContextProvider from '@/components/RecipesForm/RecipesForm.context'
import { Container, Step, StepLabel, Stepper } from '@mui/material'
import Head from 'next/head'
import { useState } from 'react'

const steps = ['Ingredients', 'Instructions', 'Review'];

export default function Home() {
  const [activeStep, setActiveStep] = useState(0);

  return (
    <>
      <Head>
        <title>Recipes Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ marginTop: 5 }}>
        <RecipesFormContextProvider>
          <Stepper activeStep={activeStep} alternativeLabel>
            {steps.map((label) => (
              <Step key={label}>
                <StepLabel>{label}</StepLabel>
              </Step>
            ))}
          </Stepper>
          {activeStep === 0 && <RecipesForm setActiveStep={setActiveStep} />}
        </RecipesFormContextProvider>
      </Container>
    </>
  )
}
